GET http://localhost:5000/api/jobs


###

POST http://localhost:8000/api/jobs
Content-Type: application/json 

{
    "company" : {
        "name" : "Slack",
        "thumbnail" : "https://cdn.worldvectorlogo.com/logos/slack-new-logo.svg",
        "tagline" :  "Come and work where the future works" 
    },
    "roleInfo" : {
        "role" : "Product Designer",
        "jobtype" : "Full-time",
        "salary": {
            "min" : 100000,
            "max" : 120000, 
        },
        "location" : "Remote",
        "roleOverview" : "We're hiring a Product Designer to help craft the future of Slack. Designers here work across every stage of product development, from crafting the experience of new features, to prototyping and finding creative solutions, to the craft and finish of every detail in the product. On our design team, we appreciate designers who think deeply, speak clearly, work collaboratively, and have an excellent collection of animated GIFs. At Slack, we have a positive, diverse, and encouraging culture — we look for people who are curious, inventive, and work to be a little better every single day.",   
        "mainResponsibilities" : [
            "Work with design, product management, and engineering to generate ideas and turn them into a flawless product experience.",
            "Work closely with senior designers on the team to define features and the overall direction of your product area.",
            "Partner with engineering to ensure a high-quality implementation and user experience.",
            "Use the Slack design system in order to craft flows, prototypes, sketches, and high-fidelity visuals for your features.",
            "Improve your team’s work by asking for and offering feedback from other product designers and cross-functional teammates."        
        ],
        "skillsReq" : [
                "2+ years of experience in an individual contributor role on a product design team for desktop or mobile",
                "An outstanding portfolio, showcasing a foundation in typography, interaction, and visual design.",
                "Solid understanding of how to craft usable, accessible, and modular designs that can scale to millions of users.",
                "Experience working and collaborating with complementary diverse teams in a multi-faceted, rapid-growth environment.",
                "Experience working with product managers to execute on the strategy for product features.",
                "Experience with prototyping as a means to explore and convey design solutions.",
                "Excellent communication skills (bonus points if you love to use emoji)"

        ],
        "dept" : "Design",
        "skillXP" : 80
    },
    "tags" : [
        "Full time", 
        "Design",
        "visual design"
    ],
    "companyInfo" : "61425c1206d9ec76fa841ed3"
}

###

POST http://localhost:8000/api/companies
Content-Type: application/json 

{
    "logo" : "https://cdn.worldvectorlogo.com/logos/slack-new-logo.svg", 
    "name" : "Slack", 
    "typeOfCorporation" : "Software", 
    "tagline" : "Come and work where the future works",
    "info" : "Slack Technologies, Inc. operates as a software company. The Company designs and develops a communication platform that provides real-time messaging, file sharing, archiving, and searching services for teams. Slack Technologies serves clients worldwide.",
    "size" : {
        "minSize" : 5000,
        "maxSize" : 10001
    }, 
    "address" : "San Francisco, United States", 
    "raised" : 18559805920,
    "culture" : {
        "youtube" : "https://www.youtube.com/watch?v=ZDs056YM4fc",
        "videoThumbnail" : "https://images.unsplash.com/photo-1574790398664-0cb03682ed1c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
    },
    "established" : 2009,
    "website" : "www.slack.com" 
}

###
POST http://localhost:5000/api/auth/register

Content-Type: application/application/json
{
    "name" : "Sayantan Samanta",
    "email" : "sssamanta789@gmail.com",
    "password" : "fghli",
    "phone" : "9163456288"
}

###
GET http://localhost:5000/api/companies

###
GET http://localhost:2000/


