GET http://localhost:5000/api/jobs


###

POST http://localhost:8000/api/jobs
Content-Type: application/json 

{
    "company" : {
        "name" : "Spotify",
        "thumbnail" : "https://cdn.worldvectorlogo.com/logos/spotify-2.svg",
        "tagline" :  "Wait! where's your coffee?" 
    },
    "roleInfo" : {
        "role" : "Podcast Account Director",
        "jobtype" : "Full-time",
        "salary": {
            "min" : 100000,
            "max" : 120000
        },
        "location" : "Remote",
        "roleOverview" : "We are looking for an outstanding Podcast Sales Specialist to join our growing team. We’re looking for someone with a proven record of revenue generation and a deep interest in podcasts and audio innovation to be a part of our expansion in Canada.  We want someone who loves podcasts and knows how to communicate their value to clients and partners. We are building the podcast business and you will be a partner for the sales team, a voice in the market from both a sales and tactical execution perspective. You should be confident, work hard, but also know how to have fun.  Above all, your work will impact the way the world engages in audio experiences.",   
        "mainResponsibilities" : [
            "Work across multiple agency departments, i.e. radio, digital, branded content and innovation teams, to sell through and deliver successful podcast campaigns",
            "Coordinate with the communications planning team and strategic planners, account directors, and buyers to create successful ad campaigns",
            "Work fluidly with internal teams and help to ensure that our podcasts are ready for monetization at scale",
            "Work closely with internal teams on operations to ensure local podcasts are set up for monetization",
            "Partner internally with sales support, marketing and Spotify Studios teams to maximize revenue for Spotify and our partners",
            "Attend/lead client meetings to present in-depth sales narrative, data, insights & research"
        ],
        "skillsReq" : [
                "You have 6+ years of experience in a media agency/online sales role; digital and podcast sales preferred.",
                "Understanding of selling a network and specific audiences",
                "You have knowledge of online and offline media and have the ability to be creative with audio and digital client solutions",
                "You are operationally proficient and can dig into the details at a campaign level", 
                "You have strong negotiation skills and the ability to present effectively and close the deal",
                "You have the ability to build a pipeline and proven track record of exceeding goals",
                "You have dexterity in creating reports and presentations using Excel, PowerPoint, Keynote, etc."
        ],
        "dept" : "Sales & Marketing",
        "skillXP" : 90
    },
    "tags" : [
        "Sales",
        "Excel",
        "Full time"
    ]
}

###

POST http://localhost:8000/api/companies
Content-Type: application/json 

{
    "logo" : "https://cdn.worldvectorlogo.com/logos/spotify-2.svg", 
    "name" : "Spotify", 
    "typeOfCorporation" : "Internet", 
    "tagline" : "Wait! where's your coffee?",
    "info" : "Spotify is a digital music, podcast, and video service that gives you access to millions of songs and other content from creators all over the world. Basic functions such as playing music are totally free,build collections of music and podcasts.",
    "size" : {
        "minSize" : 200,
        "maxSize" : 501
    }, 
    "address" : "Stockholm, Sweden", 
    "raised" : 7700000000,
    "culture" : {
        "youtube" : "https://www.youtube.com/watch?v=Vvo-2MrSgFE",
        "videoThumbnail" : "https://images.pexels.com/photos/340103/pexels-photo-340103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
    },
    "established" : 2006,
    "website" : "https://www.spotify.com" 
}

###
POST http://localhost:5000/api/auth/register

Content-Type: application/application/json
{
    "name" : "Sayantan Samanta",
    "email" : "sssamanta789@gmail.com",
    "password" : "fghli",
    "phone" : "9163456288"
}

###
GET http://localhost:5000/api/companies

###
GET http://localhost:2000/


