const AUTHENTICATING = "AUTHENTICATING";
const AUTHENTICATION_SUCESSFULL = "AUTHENTICATION_SUCESSFULL";
const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";

export { AUTHENTICATING, AUTHENTICATION_SUCESSFULL, AUTHENTICATION_FAILED }