GET http://localhost:6000/api/jobs

###

POST http://localhost:5000/api/companies

Content-Type: application/json 
{
    "logo" : "https://cdn.svgporn.com/logos/twitter.svg", 
    "name" : "Twitter", 
    "typeOfCorporation" : "Social-networking", 
    "info" : "Twitter is an open social network that people use to converse with each other in short messages, known as tweets. Whether it's sharing breaking news, posting updates about their company or following their favourite celebrities, people are using Twitter to connect with others and to discover new things every day.",
    "size" : {
        "minSize" : 200,
        "maxSize" : 1001
    }, 
    "address" : "3500 Deer Creek Road Palo Alto, CA 94304, United States of America", 
    "raised" : 721000000
}

###
POST http://localhost:5000/api/auth/register

Content-Type: application/application/json
{
    "name" : "Sayantan Samanta",
    "email" : "sssamanta789@gmail.com",
    "password" : "fghli",
    "phone" : "9163456288"
}