GET http://localhost:6000/api/jobs

###

POST http://localhost:6000/api/companies

Content-Type: application/json 
{
    "companyImageUrl" : "/tesla-motors.svg", 
    "companyName" : "Tesla Motors", 
    "typeOfCorporation" : "U-form", 
    "companySize" : "10M", 
    "companyAddress" : "3500 Deer Creek Road Palo Alto, CA 94304, United States of America", 
    "raised" : "721000000"
}