const AUTHENTICATING = 'AUTHENTICATING';
const AUTHENTICATION_SUCESSFULL = 'AUTHENTICATION_SUCESSFULL';
const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
const LOGOUT_USER = 'LOGOUT_USER';

export { AUTHENTICATING, AUTHENTICATION_SUCESSFULL, AUTHENTICATION_FAILED, LOGOUT_USER };
